name: Frontend CI

on:
  push:
    paths:
      - 'frontend/bookkeeper-frontend-1/**'
  pull_request:
    paths:
      - 'frontend/bookkeeper-frontend-1/**'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/bookkeeper-frontend-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false
